let countries = `AED-UAE Dirham -United Arab Emirates-AE,
ARS-Argentine Peso -Argentina-AR,
AUD-Australian Dollar -Australia-AU,
BGN-Bulgarian Lev -Bulgaria-BG,
BRL-Brazilian Real -Brazil-BR,
BSD-Bahamian Dollar -Bahamas-BS,
CAD-Canadian Dollar -Canada-CA,
CHF-Swiss Franc -Switzerland-CH,
CLP-Chilean Peso -Chile-CL,
CNY-Chinese Renminbi -China-CN,
COP-Colombian Peso -Colombia-CO,
CZK-Czech Koruna -Czech Republic-CZ,
DKK-Danish Krone -Denmark-DK,
DOP-Dominican Peso -Dominican Republic-DO,
EGP-Egyptian Pound -Egypt-EG,
EUR-Euro -Europe-EU,
FJD-Fiji Dollar -Fiji-FJ,
GBP-Pound Sterling -United Kingdom-GB,
GTQ-Guatemalan Quetzal -Guatemala-GT,
HKD-Hong Kong Dollar -Hong Kong-HK,
HRK-Croatian Kuna -Croatia-HR,
HUF-Hungarian Forint -Hungary-HU,
IDR-Indonesian Rupiah	-Indonesia-ID,
ILS-Israeli New Shekel -Israel-IL,
INR-Indian Rupee -India-IN,
ISK-Icelandic Krona -Iceland-IC,
JPY-Japanese Yen -Japan-JP,
KRW-South Korean Won -South Korea-KR,
KZT-Kazakhstani Tenge -Kazakhstan-KZ,
MVR-Maldivian Rufiyaa -Maldives-MV,
MXN-Mexican Peso -Mexico-MX,
MYR-Malaysian Ringgit -Malaysia-MY,
NOK-Norwegian Krone -Norway-NO,
NZD-New Zealand Dollar -New Zealand-NZ,
PAB-Panamanian Balboa -Panama-PA,
PEN-Peruvian Sol -Peru-PE,
PHP-Philippine Peso -Philippines-PH,
PKR-Pakistani Rupee -Pakistan-PK,
PLN-Polish Zloty -Poland-PL,
PYG-Paraguayan Guarani -Paraguay-PY,
RON-Romanian Leu -Romania-RO,
RUB-Russian Ruble -Russia-RU,
SAR-Saudi Riyal -Saudi Arabia-SA,
SEK-Swedish Krona -Sweden-SE,
SGD-Singapore Dollar -Singapore-SG,
THB-Thai Baht -Thailand-TH,
TRY-Turkish Lira -Turkey-TR,
TWD-New Taiwan Dollar -Taiwan-TW,
UAH-Ukrainian Hryvnia -Ukraine-UA,
USD-United States Dollar -United States-US,
UYU-Uruguayan Peso -Uruguay-UY,
ZAR-South African Rand -South Africa-ZA`;

let countryArray = countries.split(",");
export default countryArray;